spring:
  application:
    name: notification-service

  config:
    import: optional:configserver:http://configserver:8888

  data:
    mongodb:
      uri: mongodb://localhost:27017/notificationDb


management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true

server:
  port: 8084