version: "3.8"

services:

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - microservice-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: productDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  configserver:
    build:
      context: ./configserver
    container_name: configserver
    ports:
      - "8888:8888"
    depends_on:
      - mongodb
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - GIT_SSL_NO_VERIFY=true
    networks:
      - microservice-network

  eurekaserver:
    build:
      context: ./eurekaserver
    container_name: eurekaserver
    ports:
      - "8761:8761"
    depends_on:
      - configserver
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - microservice-network

  user-service:
    build:
      context: ./userService
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - configserver
      - eurekaserver
      - mongodb
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - microservice-network

  order-service:
    build:
      context: ./orderService
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      - configserver
      - eurekaserver
      - mongodb
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - microservice-network

  product-service:
    build:
      context: ./productService
    container_name: product-service
    ports:
      - "8083:8083"
    depends_on:
      - configserver
      - kafka
      - postgres
      - eurekaserver
    environment:
      SPRING_PROFILES_ACTIVE: default
    networks:
      - microservice-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - microservice-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge