#spring:
#  application:
#    name: eureka-server
#
#server:
#  port: 8761
#
#eureka:
#  client:
#    register-with-eureka: false   # Don't register Eureka server with itself
#    fetch-registry: false         # Eureka server doesn't fetch other services
#  instance:
#    hostname: eurekaserver        # Must match the container name in docker-compose
#    prefer-ip-address: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health           # Required for Docker health check
#  endpoint:
#    health:
#      show-details: always
#
#logging:
#  level:
#    com.netflix.eureka: INFO
#    org.springframework.cloud: INFO


spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: eurekaserver
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"         # Expose all actuator endpoints
  endpoint:
    health:
      show-details: always   # Show full health check details

  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    com.netflix.eureka: INFO
    org.springframework.cloud: INFO