#POST http://localhost:8081/api/kafka/publish?message=HelloKafka
#
#GET http://localhost:8761/


## Get all users

POST http://localhost:8081/api/kafka/notify-order
Content-Type: application/json


{
  "orderId": 1,
  "userId": 1,
  "productId": 1,
  "quantity": 2
}