#spring:
#  application:
#    name: product-service
#  config:
#    import: optional:configserver:http://configserver:8888
#  datasource:
#    url: jdbc:postgresql://postgres:5432/productDb
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#  profiles:
#    active: default
#
#management:
#  tracing:
#    sampling:
#      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: http://zipkin:9411/api/v2/spans
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  prometheus:
#    metrics:
#      export:
#        enabled: true
#

spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://configserver:8888
    fail-fast: true

    datasource:
      url: jdbc:postgresql://postgres:5432/productDb
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver

      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083

#server:
#  port: 8083