spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PatelPratik39/config-repo
          default-label: main
          clone-on-start: true
          skip-ssl-validation: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
server:
  port: 8888