
spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://configserver:8888

  data:
    mongodb:
      uri: mongodb://localhost:27017/userDb

server:
  port: 8081