name: CI/CD Hello World

on:
  push:
    branches: ['pratik-branch']

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Run Maven tests
        run: mvn test

      - name: Build package (skip tests)
        run: mvn package -DskipTests