name: CI/CD Hello World

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Verify Maven
        run: mvn -v

      - name: Run tests
        run: mvn test

      - name: Build & Package
#        working-directory: ./productService
        run: mvn clean package -DskipTests