name: CI/CD with Docker Compose

on:
  push:
    branches: [ "pratik-branch" ]
# Uncomment this if you want to run on pull requests too
#  pull_request:
#    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [user-service, product-service, order-service, notification-service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build all services
        run: |
          for service in user-service product-service order-service notification-service
          do
            echo "Building $service"
            cd $service
            mvn clean package -DskipTests
            docker build -t $service:latest .
            cd ..
          done

      - name: Run docker-compose
        run: docker-compose -f docker-compose.yml up -d --build
#      - name: Build ${{ matrix.service }}
#        working-directory: ${{ matrix.service }}
#        run: mvn clean package -DskipTests
#
#      - name: Build Docker image for ${{ matrix.service }}
#        working-directory: ${{ matrix.service }}
#        run: docker build -t ${{ matrix.service }}:latest .

  # Optional: Run docker-compose after all services are built
  run-docker-compose:
    runs-on: ubuntu-latest
    needs: build-and-run
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run docker-compose for integration test
        run: docker-compose -f docker-compose.yml up -d --build