name: CI/CD with Docker Compose

on:
  push:
    branches: [ "pratik-branch" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [userService, productService, orderService, notification-service, configserver]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Check Java version
        run: java -version

      - name: Build JAR for ${{ matrix.service }}
        working-directory: ./${{ matrix.service }}
        run: mvn clean package -DskipTests

      - name: Build Docker image for ${{ matrix.service }}
        working-directory: ./${{ matrix.service }}
        run: |
          IMAGE_TAG=$(echo "${{ matrix.service }}" | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE_TAG:latest .

  run-docker-compose:
    runs-on: ubuntu-latest
    needs: build-and-run

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run docker compose
        run: docker compose -f docker-compose.yml up -d --build

      - name: Validate containers are running
        run: docker ps