name: CI/CD with Docker Compose

on:
  push:
    branches: [ "pratik-branch" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [userService, productService, orderService, notification-service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Dockerize ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: |
          mvn clean package -DskipTests
          docker build -t ${{ matrix.service }}:latest .

  run-docker-compose:
    runs-on: ubuntu-latest
    needs: build-and-run
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run docker-compose
        run: docker-compose -f docker-compose.yml up -d --build